### ISSUE TITLE
Competition UI clarification

### ISSUE THREAD

**Issue by Charles-Hoot** [sudheera96/Group-4--Hunt-game#10]
When I go to join a competition, what does the UI do?   Drop down my teams?  What if I am a member, but not a captain?

**Comment by GBunnuD** [comment]
When the user clicks on the competition, The UI will have a pop-up asking to join or leave.
If the user is not a captain, then the user will not be able to join the competition. Only the captain can join the competition.
If the user clicks the competition(not captain), if he is enrolled in the competition by the team captain then the user can view or play the Quests.
