### ISSUE TITLE
Missing UI

### ISSUE THREAD

**Issue by Charles-Hoot** [sudheera96/Group-4--Hunt-game#11]
How do I play the game?

**Comment by GBunnuD** [comment]
Added the gameplay UI design image.

**Comment by sudheera96** [comment]
@GD-Prasad , I think we need to provide the suggestions and directions on what to click to accesses what in the game after the player login. Because, few people randomly download the game without any idea. So for them, it would be better. So, How about if we look into such type of UI designs.

**Comment by GBunnuD** [comment]
Okay, I will update the UI and it's description to display the rules.
