### ISSUE TITLE
User Role confusion

### ISSUE THREAD

**Issue by Charles-Hoot** [sudheera96/Group-4--Hunt-game#4]
Developer team roles are not the same as user roles.

**Comment by GBunnuD** [comment]
No, Developer team roles are not the same as user roles.
The user will be able to create competition, add locations, and create Quests. The developer will have complete rights on the application. 
The user who creates the quest or competition or location will not be able to play as a player.

**Comment by sudheera96** [comment]
> No, Developer team roles are not the same as user roles.
> The user will be able to create competition, add locations, and create Quests. The developer will have complete rights on the application.
> The user who creates the quest or competition or location will not be able to play as a player.

@GD-Prasad,  please update in the readme as well.

**Comment by sudheera96** [comment]
> Developer team roles are not the same as user roles.

@Charles-Hoot , Hope the provided details were resolved your confusion. In that hope, we are closing this issue. 
Kindly please open the issue again if you need any further clarification.
