### ISSUE TITLE
Sample Data

### ISSUE THREAD

**Issue by Charles-Hoot** [sudheera96/Group-4--Hunt-game#7]
Looks like Swaroop started a team.  Should they also be in the team/player table?

If a player can be on more than one team, you should probably create sample data that has that situation.

**Comment by krishna-s-koyyalamudi** [comment]
Swaroop has started a team as a user. He should be in the Team he has created. He cannot be in multiple teams at same instance however he can create/join another team once the current participating competition has ended.

I have added the sample data and modified the spreadsheet and markdown.
